#pragma once

namespace ntt {

enum ImageType
{
	IMAGE_TYPE_1D,
	IMAGE_TYPE_2D,
	IMAGE_TYPE_3D,
	IMAGE_TYPE_COUNT
};

enum Format
{
	FORMAT_R8G8B8A8_SRGB,
	FORMAT_B8G8R8A8_SRGB,
	FORMAT_COUNT
};

enum ShaderStage
{
	SHADER_STAGE_VERTEX,
	SHADER_STAGE_TESSELATION_CONTROL,
	SHADER_STAGE_TESSELATION_EVALUATION,
	SHADER_STAGE_GEOMETRY,
	SHADER_STAGE_FRAGMENT,
	SHADER_STAGE_COUNT
};

ShaderStage getShaderStageFromFileName(const char* filename);

} // namespace ntt
