macro(ntt_configure)
    set(BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/..")

    option(CMAKE_BUILD_TYPE "Build type" "Debug") 
    set(TARGET_COMPILE_OPTIONS)
    set(TARGET_DEFINITIONS)

    if (CMAKE_BUILD_TYPE STREQUAL "Release")
        list(APPEND TARGET_COMPILE_OPTIONS "-DDEBUG=0" "-O3" "-DNDEBUG")
        list(APPEND TARGET_DEFINITIONS "NTT_DEBUG=0")
    elseif (CMAKE_BUILD_TYPE STREQUAL "Test")
        list(APPEND TARGET_DEFINITIONS "NTT_TEST=1")
        list(APPEND TARGET_COMPILE_OPTIONS "-DDEBUG=1" "-O0" "-g" "-DRUN_TESTS=1")
    else()
        list(APPEND TARGET_COMPILE_OPTIONS "-DDEBUG=1" "-O0" "-g")
        list(APPEND TARGET_DEFINITIONS "NTT_DEBUG=1")
    endif()

    ntt_platform_detect()

    ntt_option("NTT_ENGINE_BINDING" "ON")

    if (MSVC)
    else()
        add_compile_options(-Wall -Werror)
    endif()
endmacro()

macro(ntt_platform_detect)
    set(NTT_PLATFORM_WINDOWS FALSE)
    set(NTT_PLATFORM_LINUX FALSE)
    set(NTT_PLATFORM_MACOS FALSE)
    set(NTT_PLATFORM_WEB FALSE)

    if (WIN32)
        list(APPEND TARGET_DEFINITIONS "NTT_PLATFORM_WINDOWS=1")
        set(NTT_PLATFORM_WINDOWS TRUE)
        message("Building for Windows")
    elseif(APPLE)
        list(APPEND TARGET_DEFINITIONS "NTT_PLATFORM_MACOS=1")
        set(NTT_PLATFORM_MACOS TRUE)
        message("Building for MacOS")
    elseif(UNIX)
        set(NTT_PLATFORM_LINUX TRUE)
        message("Building for Linux")
        list(APPEND TARGET_DEFINITIONS "NTT_PLATFORM_LINUX=1")
    elseif(EMSCRIPTEN)
        set(NTT_PLATFORM_WEB TRUE)
        message("Building for WebAssembly")
        list(APPEND TARGET_DEFINITIONS "NTT_PLATFORM_WEB=1")
    endif() 

    if (MSVC)
        list(APPEND TARGET_DEFINITIONS "NTT_COMPILER_MSVC=1")
    endif()
endmacro()


macro(ntt_option OPTION_NAME OPTION_DEFAULT)
    option(${OPTION_NAME} "${OPTION_NAME} value" ${OPTION_DEFAULT}) 

    if(${OPTION_NAME} STREQUAL "ON" OR ${OPTION_NAME} STREQUAL "1" OR ${OPTION_NAME} STREQUAL "TRUE")
        list(APPEND TARGET_DEFINITIONS ${OPTION_NAME}=1)
    elseif(${OPTION_NAME} STREQUAL "OFF" OR ${OPTION_NAME} STREQUAL "0" OR ${OPTION_NAME} STREQUAL "FALSE")
        list(APPEND TARGET_DEFINITIONS ${OPTION_NAME}=0)
    else()
        list(APPEND TARGET_DEFINITIONS ${OPTION_NAME}=${${OPTION_NAME}})
    endif()
endmacro()

macro(ntt_print_configuration)
    message(STATUS "CMake Build Type: ${CMAKE_BUILD_TYPE}")
    message(STATUS "Target Compile Options: ${TARGET_COMPILE_OPTIONS}")

    foreach(DEFINITION ${TARGET_DEFINITIONS})
        message(STATUS " - ${DEFINITION}")
    endforeach()
    
endmacro()

macro(ntt_find_package PACKAGE_NAME FOLDER)
    if (MSVC)
        set(CMAKE_FOLDER ${FOLDER})
    endif()

    set(${PACKAGE_NAME}_DIR ${BASE_DIRECTORY}/cmake)
    find_package(${PACKAGE_NAME} REQUIRED)

    if (MSVC)
        unset(CMAKE_FOLDER)
    endif()
endmacro()
